version: "3.9"

services:
  crawler:
    build: .
    image: ${DOCKER_USERNAME}/crawler_app:latest
    container_name: crawler_app
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./exports:/app/exports
      - ./tmp_cookies_shared.json:/app/tmp_cookies_shared.json
    networks:
      - crawler_net
networks:
  crawler_net:
    driver: bridge
